Repository publdaze/js-study, pull requests merged in 2024-05, with the labels that each got.

#5 publdaze: [변수] 훑어보기
  변수/김은지.md
Labels: 1주차, 변수

#6 publdaze: [변수] 1. 데이터 in 메모리
  README.md
  변수/김은지.md
Labels: 1주차, 변수

#7 publdaze: [변수] 2~3. 변수와 식별자
  변수/김은지.md
Labels: 1주차, 변수

#25 publdaze: [변수] 4~5. 변수 선언과 값의 할당/재할당
  변수/김은지.md
Labels: 1주차, 변수

#26 publdaze: [데이터 타입] 훑어보기
  README.md
  데이터 타입/김은지.md
Labels: 1주차, 데이터 타입

#42 publdaze: [스코프] 훑어보기
  README.md
  스코프/김은지.md
Labels: 2주차, 스코프

#43 publdaze: [전역 변수의 문제점] 훑어보기
  README.md
  전역 변수의 문제점/김은지.md
Labels: 2주차, 전역 변수의 문제점

#49 pipisebastian: [데이터 타입] 질문답변 정리Pipisebastian
  README.md
  데이터 타입/장서윤.md
Labels: 1주차, 데이터 타입
